
spring:
  application:
    name: reactive-lab

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.esey4mr.mongodb.net/indications?retryWrites=true&w=majority


